version: '3.7'

services:
  SQLsecure:
    image: php:7.4-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www